config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'omni_auth'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
  end
  resources :glucoses

  get 'generate_report', to: 'glucoses#generate_report'
  get 'report_details', to: 'glucoses#report_details'


  root to: 'application#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/glucose.rb
class Glucose < ApplicationRecord
    belongs_to :user
    validates :level, presence: true
    before_create :check_record_count

    def check_record_count
        readings = self.user.glucoses.where(reading_date: Date.today).count
        if readings >= 4
            errors.add :base, "You can't save more then 4 readings per day."
            throw :abort
        end
    end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github]
  has_many :glucoses       

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def home; end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up)
    devise_parameter_sanitizer.permit(:account_update)
  end
end

app/controllers/glucoses_controller.rb
class GlucosesController < ApplicationController
    def new
        @glucose = Glucose.new
    end

    def create
        glucose = Glucose.new(glucose_params.merge(user_id: current_user.id))
        if glucose.save
            redirect_to root_path, notice: 'Your record successfully saved!'
        else
            redirect_to root_path, alert: '' + glucose.errors.full_messages.first
        end
    end

    def generate_report

    end

    def report_details
        if params[:date].present?
            @readings = current_user.glucoses&.where(reading_date: params[:date])
        elsif params[:start_date].present?
            @readings = current_user.glucoses&.where(reading_date: params[:start_date]..params[:end_date])
        else
            redirect_to generate_report_path, alert: 'In valid options selected!'
        end 
        flash.now[:alert] = 'There is no data available in this period' unless @readings.present?
        if @readings.present?
            levels = @readings.pluck(:level)
            @maximum = levels.max
            @minimum = levels.min
            @average = levels.inject{ |sum, el| sum + el }.to_f / levels.size
        end
    end

    private
    
    def glucose_params
        params.require(:glucose).permit(:level, :reading_date)
    end
end

app/controllers/omni_auth_controller.rb
class OmniAuthController < Devise::OmniauthCallbacksController
    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(_resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(_resource)
    root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/glucoses_helper.rb
module GlucosesHelper
end

app/helpers/omni_auth_helper.rb
module OmniAuthHelper
end

app/views/application/home.html.erb
<section class="text-center m-5">
    <h1 class="text-center" >Welcome To Blood Glucose tracker</h1>
    <p>Click here to add a new record</p>
    <%= link_to('Add Reading', new_glucose_path, class: 'btn btn-primary m-5') %>
    <%= link_to('Generate Report', generate_report_path, class: 'btn btn-secondary m-5') %>
    <%=
        link_to_if(current_user.nil?, "Login", sign_in_path, class: 'btn btn-primary m-5') do
            link_to('Sign out',  destroy_user_session_path, :method => 'delete', class: 'btn btn-danger m-5')
        end
    %>

</section>

app/views/glucoses/generate_report.html.erb
<h2 class="text-center m-5">Report Generator</h2>
<section class="col-8 offset-2 col-sm-6 offset-sm-3">

<%= form_with url: "/report_details", method: :get, local: true do |form| %>
  <div class="field">
    <%= form.label :type, "Select Type:" %><br />
    <%= form.select(:type, [['daily', 1], ['monthly', 2]], {:include_blank => 'Select type'}, { class: 'form-control m-2 date-type'}) %>
  </div>

  <div class="field daily d-none">
    <%= form.label :date, "Select date:" %><br />
    <%= form.date_field :date, { class: "form-control m-2" } %>
  </div>

  <div class="field start-date d-none">
    <%= form.label :start_date, "Select start date:" %><br />
    <%= form.date_field :start_date, { class: "form-control m-2" } %>
  </div>

  <div class="field end-date d-none">
    <%= form.label :end_date, "Select end date:" %><br />
    <%= form.date_field :end_date, { class: "form-control m-2" } %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: 'btn btn-primary m-2'  %>
  </div>
<% end %>

<hr>
</section>


<script>
$(document).ready(function(){
    $(".date-type").change(function () {
        id = $(this).val()
        if(id == 1){
            $(".daily").removeClass("d-none");
            $(".start-date").addClass("d-none");
            $(".end-date").addClass("d-none");
            
        }else if(id == 2){
            $(".daily").addClass("d-none");
            $(".start-date").removeClass("d-none");
            $(".end-date").removeClass("d-none");
        }
    });
});
</script>

app/views/glucoses/new.html.erb
<h2 class="text-center m-5">Add Glucose Level</h2>
<section class="col-8 offset-2 col-sm-6 offset-sm-3">
<%= form_for(@glucose, url: glucoses_path(@glucose)) do |f| %>

  <div class="field">
    <%= f.label :Level %><br />
    <%= f.number_field :level, autofocus: true, autocomplete: "level", class: 'form-control m-2'  %>
    <%= f.hidden_field :reading_date, :value => Date.today  %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: 'btn btn-primary m-2'  %>
  </div>
<% end %>
<hr>
</section>

app/views/glucoses/report_details.html.erb
<h2 class="text-center m-5">Report</h2>
<section class="col-8 offset-2 col-sm-6 offset-sm-3">
    <table class="table">
        <thead class="thead-light">
            <tr>
            <th scope="col">Sr.no</th>
            <th scope="col">Level</th>
            <th scope="col">Date</th>
            </tr>
        </thead>
        <tbody>
            <% @readings&.each_with_index do |reading, index| %>
                <tr>
                    <th scope="row"><%= index + 1 %></th>
                    <td><%= reading.level %></td>
                    <td><%= reading.reading_date %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <table class="table">
        <thead class="thead-light">
            <tr>
            <th scope="col">Maximum</th>
            <th scope="col">Minimum</th>
            <th scope="col">Average</th>
            </tr>
        </thead>
        <tbody>
            <% if @readings.present? %>
                <tr>
                    <td><%= @maximum %></td>
                    <td><%= @minimum %></td>
                    <td><%= @average.round(2) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= link_to('Back', generate_report_path, class: 'btn btn-secondary mb-5') %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Rails 6 Devise Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash&.each do |type, msg| %>
      <div class="alert alert-info text-center">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<section class="m-3 d-flex justify-content-between">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
  <% end %>

</section>